### ISSUE TITLE
Missing mapping object in Report.DataSource interface!

### ISSUE THREAD

**Issue by brahim-slimani** [WebDataRocks/ngx-webdatarocks#1]
The mapping object is missing for datasource in the pivot report interface, which causes a nullable IDs for cells (WebDataRocks.CellData), normally it's expected to set a mapping for the cell IDs such :

```
reportTemplate: WebDataRocks.Report = {
    dataSource: {
      filename: 'custom-csv-filepath',
      mapping: {
        id: {
          type: 'id',
        }
      },
      formats: [
        {
          name: 'csv'
        }
      ]
    }
  };
```

Here is the datasource interface which doesn't contain the mapping property : 

![image](https://github.com/WebDataRocks/ngx-webdatarocks/assets/36894964/b146df38-8ce2-4ffa-a65e-6bb0508deba0)

Is there any workaround to fix that ?!, In such manner that the cell IDs will be encapsulated in WebDataRocks.CellData

**Comment by maksymkaD** [comment]
Hello, 

Thank you for writing to us.
Please note that WebDataRocks does not support using the mapping object in report for CSV data sources. Instead, we recommend using data type prefixes: https://www.webdatarocks.com/doc/data-type-prefixes/
These prefixes should be added to field names in the first data record to modify data types of corresponding fields.

Kind regards,
Maksym
